export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const FETCH_PROJECTS_SUCCESSS = "FETCH_PROJECTS_SUCCESSS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";

export const FETCH_PROJECT_BY_ID_REQUEST = "FETCH_PROJECT_BY_ID_REQUEST";
export const FETCH_PROJECT_BY_ID_SUCCESSS = "FETCH_PROJECT_BY_ID_SUCCESSS";
export const FETCH_PROJECT_BY_ID_FAILURE = "FETCH_PROJECT_BY_ID_FAILURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESSS = "CREATE_PROJECT_SUCCESSS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const SEARCH_PROJECT_REQUEST = "SEARCH_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESSS = "SEARCH_PROJECT_SUCCESSS";
export const SEARCH_PROJECT_FAILURE = "SEARCH_PROJECT_FAILURE";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESSS = "DELETE_PROJECT_SUCCESSS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const INVITE_TO_PROJECT_REQUEST = "INVITE_TO_PROJECT_REQUEST";
export const INVITE_TO_PROJECT_SUCCESSS = "INVITE_TO_PROJECT_SUCCESSS";
export const INVITE_TO_PROJECT_FAILURE = "INVITE_TO_PROJECT_FAILURE";

export const ACCEPT_INVITATION_REQUEST = "ACCEPT_INVITATION_REQUEST";
export const ACCEPT_INVITATION_SUCCESSS = "ACCEPT_INVITATION_SUCCESSS";
export const ACCEPT_INVITATION_FAILURE = "ACCEPT_INVITATION_FAILURE";
